import * as ExcelJS from "exceljs";
import * as fs from "fs";
import * as path from "path";
import * as oboe from "oboe";
import { GoogleSheetXlsxTemplateAction } from "../src/actions/google_sheet_xlsx_template/google_sheet_xlsx_template";

async function runSimulation() {
  const templatePath = path.resolve(__dirname, "./template-example.xlsx");
  const jsonPath = path.resolve(__dirname, "./example-json_detail_lite_stream2.json");
  const outputPath = path.resolve(__dirname, "./output.xlsx");

  console.log(`🚀 Starting local template simulation...`);
  console.log(`📂 Template Path: ${templatePath}`);
  console.log(`📂 Data Path:     ${jsonPath}`);

  // 1. Harvest JSON stream data
  let fields: any = null;
  let appliedFilters: any = null;
  const data: any[] = [];

  const downloadStream = fs.createReadStream(jsonPath);
  await new Promise<void>((resolve, reject) => {
    oboe(downloadStream)
      .node({
        "!.fields": (fieldData: any) => {
          fields = fieldData;
          return oboe.drop;
        },
        "!.applied_filters": (filters: any) => {
          appliedFilters = filters;
          return oboe.drop;
        },
        "!.data.*": (row: any) => {
          data.push(row);
          return oboe.drop;
        },
      })
      .done(() => {
        console.log(`✅ Harvested ${data.length} rows of data from JSON stream.`);
        resolve();
      })
      .fail((errorReport: any) => {
        reject(new Error(`Stream parse error: ${errorReport.message || JSON.stringify(errorReport)}`));
      });
  });

  // 2. Setup context
  const context = {
    webhookId: "local-simulation",
    lookerVersion: "23.0.0",
    type: "query",
    params: {},
    formParams: {
      filename: "Simulation Report",
    },
    scheduledPlan: {
      title: "Simulation Test Plan",
      scheduledPlanId: 999,
      downloadUrl: "http://local-simulation",
    },
    fields,
    appliedFilters,
    data,
    _built_in: {
      run_at: new Date().toISOString(),
      title: "Simulation Test Plan",
      description: "Generated by local simulation script",
    },
  };

  // 3. Load Excel workbook
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(templatePath);

  // 4. Instantiate Action and populate
  const action = new GoogleSheetXlsxTemplateAction();
  const errors = new Set<string>();

  console.log("⚙️ Populating Excel template with harvested data...");
  // Bypass private modifier via cast to 'any'
  (action as any).populateTemplate(workbook, context, errors);

  if (errors.size > 0) {
    console.warn(`⚠️ Encountered ${errors.size} unresolved mustaches. Adding _errors worksheet...`);
    const errorsSheet = workbook.addWorksheet("_errors");
    Array.from(errors).forEach((err) => {
      errorsSheet.addRow([`Could not find ${err}`]);
    });
  }

  // 5. Save output
  console.log(`💾 Saving output to: ${outputPath}`);
  await workbook.xlsx.writeFile(outputPath);
  console.log("🎉 Simulation complete! You can now view output.xlsx locally.");
}

runSimulation().catch((err) => {
  console.error("❌ Simulation failed:", err);
});
