name: Merge to Main

on:
  push:
    branches:
      - main

env:
  REGION: us-central1
  SERVICE_NAME: google-sheets-excel-template
  APP_NAME: looker-action


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TAG
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set IMAGE_NAME
        run: echo "IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}/${{ env.SERVICE_NAME }}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          # Build and push the image with both the release tag and latest
          gcloud builds submit . \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --gcs-log-dir=gs://${{ secrets.GCP_LOGS_BUCKET_NAME }}/${{ env.APP_NAME }}

      - name: Trigger Website Deploy
        run: |
          curl -fSL "$DEPLOY_URL"
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}

      - name: Save Image Name
        run: echo "${{ env.IMAGE_NAME }}:${{ env.TAG }}" > image-name.txt

      - name: Upload Image Name Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-name
          path: image-name.txt
